### ISSUE TITLE
Post Install Fail

### ISSUE THREAD

**Issue by lothsun** [dabit3/react-native-hackathon-starter#55] opened 2018-05-14 02:29 UTC
I have tried cloning and doing an npm i on the directory and this is what I get:

react-native-elements-app@1.0.0 postinstall /Users/blainehuff/Documents/Projects/demario/react-native-elements-app
> git submodule update

fatal: destination path '/Users/blainehuff/Documents/Projects/demario/react-native-elements-app/node_modules/react-native-elements' already exists and is not an empty directory.
fatal: clone of 'git@github.com:react-native-training/react-native-elements.git' into submodule path '/Users/blainehuff/Documents/Projects/demario/react-native-elements-app/node_modules/react-native-elements' failed
Failed to clone 'node_modules/react-native-elements'. Retry scheduled
fatal: destination path '/Users/blainehuff/Documents/Projects/demario/react-native-elements-app/node_modules/react-native-elements' already exists and is not an empty directory.
fatal: clone of 'git@github.com:react-native-training/react-native-elements.git' into submodule path '/Users/blainehuff/Documents/Projects/demario/react-native-elements-app/node_modules/react-native-elements' failed
Failed to clone 'node_modules/react-native-elements' a second time, aborting
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-elements-app@1.0.0 postinstall: `git submodule update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-elements-app@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blainehuff/.npm/_logs/2018-05-14T02_01_51_246Z-debug.log
[2018-05-14T02_01_51_246Z-debug.log](https://github.com/react-native-training/react-native-elements-app/files/1999215/2018-05-14T02_01_51_246Z-debug.log)

**Comment by xavier-villelegier** [comment] 2018-05-14 07:28
@lothsun The setup for this app has to be reworked. In the meantime you can run
```sh
rm -rf node_modules/react-native-elements && git submodule update
```

**Comment by xavier-villelegier** [comment] 2018-05-14 07:31
Duplicate of #50

**Closed as completed by xavier-villelegier** 2018-05-14 07:31 UTC

**Comment by rahamin1** [comment] 2018-06-21 14:47
@lothsun @xavier-villelegier 
## Hmmm... I am probably doing something stupid, but please help...

## I typed the following on my Windows 10 PC:
`git clone --recursive https://github.com/react-native-training/react-native-elements-app.git`

## and received:
```
Cloning into 'react-native-elements-app'...
remote: Counting objects: 1303, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 1303 (delta 14), reused 19 (delta 7), pack-reused 1272
Receiving objects: 100% (1303/1303), 6.08 MiB | 2.34 MiB/s, done.
Resolving deltas: 100% (653/653), done.
Submodule 'node_modules/react-native-elements' (git@github.com:react-native-training/react-native-elements.git) registered for path 'node_modules/react-native-elements'
Cloning into 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:react-native-training/react-native-elements.git' into submodule path 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements' failed
Failed to clone 'node_modules/react-native-elements'. Retry scheduled
Cloning into 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:react-native-training/react-native-elements.git' into submodule path 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements' failed
Failed to clone 'node_modules/react-native-elements' a second time, aborting
```

## Following the instructions above:

- I deleted the node_modules\react-native-elements folder
- In the `react-native-elements-app` folder I typed:  `git submodule update`
- And I get:
```
Cloning into 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:react-native-training/react-native-elements.git' into submodule path 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements' failed
Failed to clone 'node_modules/react-native-elements'. Retry scheduled
Cloning into 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:react-native-training/react-native-elements.git' into submodule path 'C:/esites-native/react-native-elements-app/node_modules/react-native-elements' failed
Failed to clone 'node_modules/react-native-elements' a second time, aborting
```
## What am I doing wrong? How can I fix this?
